set(SOURCES
  components/components.hh
  components/fwd.hh
  components/movement.hh
  components/sprite.hh
  spritesheet/fwd.hh
  spritesheet/spritesheet.cc
  spritesheet/spritesheet.hh
  viewport/fwd.hh
  viewport/viewport.cc
  viewport/viewport.hh
  world/builder.cc
  world/builder.hh
  world/fwd.hh
  world/world.hh
)