set(SOURCES
  camera/camera.cc
  camera/camera.hh
  camera/fwd.hh
  components/common.hh
  components/fwd.hh
  components/movement.hh
  components/sprite.cc
  components/sprite.hh
  spritesheet/fwd.hh
  spritesheet/spritesheet.cc
  spritesheet/spritesheet.hh
  viewport/fwd.hh
  viewport/viewport.cc
  viewport/viewport.hh
  world/builder.cc
  world/builder.hh
  world/fwd.hh
  world/world.hh
)