#pragma once

#ifndef YUMEAMI_COMPONENT
#define YUMEAMI_COMPONENT
#endif // !YA_COMPONENT

#ifndef YUMEAMI_VIEWPORT_SCALE_DENOMINATOR
#define YUMEAMI_VIEWPORT_SCALE_DENOMINATOR 2
#endif // !VIEWPORT_SCALE_DENOMINATOR
