set(SOURCES
  defines.hh
  grid/fwd.hh
  grid/grid.hh
  raii/fwd.hh
  raii/render_texture.cc
  raii/render_texture.hh
  raii/texture.cc
  raii/texture.hh
  types/direction.cc
  types/direction.hh
  types/fwd.hh
  types/vector.hh
  units/fwd.hh
  units/px.hh
  units/tile.hh
  units/tx.hh
)